### PR TITLE
string: Fix compilation of AArch64 strrchr with Clang

### PR DESCRIPTION
**Pull request by xboxfanj**

### CODE REVIEW

**Comment by xboxfanj** [comment]
Already signed the Contributor Agreement, so this should be good to go.

**Comment by nsz-arm** [comment]
thanks for the patch, i will have to sort out things internally, so it will take some time to apply your patch, but it is good (also affects newlib).

**Comment by xboxfanj** [comment]
Sounds good, thanks

**Comment by nsz-arm** [comment]
committed

**Comment by xboxfanj** [comment]
That was fast, thanks!

**Pull request closed without merging**
